[workspace]

members = [
    "horus_common",
    "horus_finance",
    "horus_data_streams",
    "horus_exchanges",
    "horus_backtesting",
    "horus_strategies",
    "horus_autoquant",
    "horus_agent",
    # "horus_terminal/src-tauri"
]