[package]
name = "horus_reporters"
version = "0.1.0"
edition = "2021"

[dependencies]
# INTERNAL
horus_finance = { path = "../horus_finance" }

# EXTERNAL
heapless = "0.7.10"
smartstring = "1.0.1"
colored = "2.0.0"