[package]
name = "horus_exchanges"
version = "0.1.0"
edition = "2021"

[dependencies]
# INTERNAL
horus_finance = { path = "../horus_finance" }

# EXTERNAL
futures = "0.3.21"
reqwest = "0.11.9"
serde = "1.0"
serde_json = "1.0"