[package]
name = "horus_order_routing"
version = "0.1.0"
edition = "2021"

[dependencies]
horus_finance = { path = "../horus_finance" }
futures = "0.3.21"
reqwest = "0.11.9"
serde = "1.0"
serde_json = "1.0"