name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Clippy
      run: rustup component add clippy

    - name: Install WASM target
      run: rustup target add wasm32-unknown-unknown

    - name: Build
      run: cargo build --verbose

    - name: Run unit tests
      run: cargo test --verbose
    
    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features